version: '3.3'
services:
  laminas:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - backend

  mysql:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'toor'
      MYSQL_PASSWORD: 'toortoor'
      MYSQL_ROOT_PASSWORD: 'toortoor'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend
volumes:
  my-db:
networks:
  backend:
    driver: bridge